---
name: eliud_pkg_medium_model
description: eliud_pkg_medium_model is the model package for the package eliud_pkg_medium. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_medium_model
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  camera: ^0.10.5
  chewie: ^1.7.1
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  crop_your_image: ^0.7.5
  datetime_picker_formfield_new: ^2.1.0
  easy_image_viewer: ^1.2.1
  eliud_core:
    path: ../eliud_core
  eliud_core_model:
    path: ../eliud_core_model
  eliud_core_main:
    path: ../eliud_core_main
  eliud_core_helpers:
    path: ../eliud_core_helpers
  equatable: ^2.0.5
  file_picker: ^5.2.0+1
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  meta: ^1.9.1
  percent_indicator: ^4.2.3
  pinch_zoom: ^2.0.0
  tuple: ^2.0.2
  video_player: ^2.8.1
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
